sudo apt install -y cmake
sudo apt install -y libc-ares-dev
sudo apt install -y libicu-dev
sudo apt install -y libctemplate-dev
sudo apt install -y libtidy-dev
sudo apt install -y uuid-dev
sudo apt install -y libxml2-dev
sudo apt install -y libsasl2-dev
sudo apt install -y liblzma-dev
